//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJAS_Descuento
    {
        public int Año { get; set; }
        public int IdTipo { get; set; }
        public double Porcentaje { get; set; }
        public bool Activo { get; set; }
    
        public virtual CAT_CAJAS_TipoDeDescuento CAT_CAJAS_TipoDeDescuento { get; set; }
    }
}
