//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJAS_HistorialPagosCancelados
    {
        public int Id { get; set; }
        public Nullable<long> Folio { get; set; }
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
        public string TipoDePago { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> CantidadDeBimestres { get; set; }
        public Nullable<decimal> CantidadAñoActual { get; set; }
        public Nullable<decimal> CantidadAño_5 { get; set; }
        public Nullable<decimal> CantidadAño_4 { get; set; }
        public Nullable<decimal> CantidadAño_3 { get; set; }
        public Nullable<decimal> CantidadAño_2 { get; set; }
        public Nullable<decimal> CantidadAño_1 { get; set; }
        public Nullable<int> Año { get; set; }
    }
}
