//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJAS_DatosTrasladoRecibo
    {
        public int Id { get; set; }
        public string NombreAdjunto { get; set; }
        public string NroTramite { get; set; }
        public string CambioNombre { get; set; }
        public Nullable<int> FolioOperacion { get; set; }
    }
}
