//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJAS_HistorialBancos
    {
        public int Id { get; set; }
        public Nullable<long> Folio { get; set; }
        public Nullable<int> IdFormaDePago { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> FolioUsado { get; set; }
        public string ReferenciaBanco { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
    }
}
