//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJAS_HistorialUsuariosBaja
    {
        public int id { get; set; }
        public string NombreUbicacionDePago { get; set; }
        public System.DateTime FechaDeBaja { get; set; }
        public Nullable<int> IdUsuarioDeCobro { get; set; }
        public Nullable<int> IdUsuarioBaja { get; set; }
    }
}
