//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJAS_HistorialTraslados
    {
        public int FolioTraslado { get; set; }
        public string TipoOperacion { get; set; }
        public Nullable<decimal> ValorSobre { get; set; }
        public Nullable<decimal> Cobro { get; set; }
        public string TipoDePago { get; set; }
        public Nullable<int> Año { get; set; }
    }
}
