//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJAS_Traslado
    {
        public int Id { get; set; }
        public int IdFolioCajas { get; set; }
        public int IdTipoOperacion { get; set; }
        public string NombreSolicitante { get; set; }
        public string ApellidoPaternoSolicitante { get; set; }
        public string ApellidoMaternoSolicitante { get; set; }
        public int IdUsuario { get; set; }
        public int año { get; set; }
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
        public string ClaveCatastral { get; set; }
        public string NroTramite { get; set; }
    }
}
