//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJAS_HistorialPredioTraslados
    {
        public long Id { get; set; }
        public int FolioTraslado { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
        public string RFC { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public Nullable<int> CodigoPostal { get; set; }
        public string Ubicacion { get; set; }
    }
}
