//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJAS_HistorialPago
    {
        public int IdPago { get; set; }
        public int FolioOperacion { get; set; }
        public decimal Cantidad { get; set; }
        public int IdFormaDePago { get; set; }
        public int IdUbicacionDePago { get; set; }
        public System.DateTime FechaDePago { get; set; }
        public System.DateTime FechaDeCancelacion { get; set; }
        public string MotivoCancelacion { get; set; }
        public int idUsuario { get; set; }
        public string referencia { get; set; }
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
        public string NombreSolicitante { get; set; }
        public string ApellidoPaternoSolicitante { get; set; }
        public string ApellidoMaternoSolicitante { get; set; }
        public int idUsuarioCobro { get; set; }
    }
}
