//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANCELADO_CAJAS_PagosPredial
    {
        public int IdPago { get; set; }
        public Nullable<int> IdFolio { get; set; }
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
        public string NombreSolicitante { get; set; }
        public string ApellidoPaternoSolicitante { get; set; }
        public string ApellidoMaternoSolicitante { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> BimestresPagados { get; set; }
        public Nullable<int> AñoPagado { get; set; }
        public Nullable<int> FolioOperacion { get; set; }
    }
}
