//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANCELADO_CAJAS_Pago
    {
        public int IdPago { get; set; }
        public Nullable<int> IdFolio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public int IdFormaDePago { get; set; }
        public int IdUbicacionDePago { get; set; }
        public Nullable<System.DateTime> FechaDePago { get; set; }
        public int IdUsuarioDeCobro { get; set; }
        public string Referencia { get; set; }
    }
}
