//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANCELADO_SIS_Info_Manzanas
    {
        public int id { get; set; }
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
        public string Manzana { get; set; }
        public string Lote { get; set; }
        public string Parcela { get; set; }
        public string Zona { get; set; }
    }
}
