//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TRASLADOS_PagoMinimoAvaluo
    {
        public int id { get; set; }
        public decimal valorMinimoAvaluo { get; set; }
        public decimal valorPorcentajeAvaluo { get; set; }
        public string descripcion { get; set; }
        public int año { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public System.DateTime fechaModificacion { get; set; }
    }
}
