//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TipoConstruccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_TipoConstruccion()
        {
            this.SIS_DetallesDeTerreno = new HashSet<SIS_DetallesDeTerreno>();
            this.SIS_DetallesDeTerreno_Temporal = new HashSet<SIS_DetallesDeTerreno_Temporal>();
        }
    
        public int Id { get; set; }
        public string NombreConstruccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIS_DetallesDeTerreno> SIS_DetallesDeTerreno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIS_DetallesDeTerreno_Temporal> SIS_DetallesDeTerreno_Temporal { get; set; }
    }
}
