//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_JefesDepartamentos
    {
        public int id { get; set; }
        public string nombreDepartamento { get; set; }
        public string nombreDirector { get; set; }
        public string apellidoPaternoDirector { get; set; }
        public string apellidoMaternoDirector { get; set; }
        public string abreviaturaPuesto { get; set; }
    }
}
