//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_CAJAS_UbicacionDePago
    {
        public int Id { get; set; }
        public string NombreUbicacionDePago { get; set; }
        public System.DateTime FechaDeAlta { get; set; }
        public int IdUsuarioDeAlta { get; set; }
        public Nullable<int> IdUbicacionCaja { get; set; }
        public Nullable<int> IdUbicacionColonia { get; set; }
        public Nullable<int> IdTipoCaja { get; set; }
        public Nullable<int> IdUsuarioDeCobro { get; set; }
    }
}
