//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TRASLADOS_Dependencias
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string titularNombre { get; set; }
        public string titularApellidoPaterno { get; set; }
        public string titularApellidoMaterno { get; set; }
    }
}
