//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TRASLADOS_TipoProceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_TRASLADOS_TipoProceso()
        {
            this.TRA_FlujoxProceso = new HashSet<TRA_FlujoxProceso>();
            this.TRA_Tramite = new HashSet<TRA_Tramite>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string movimiento { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<int> IdTipoProceso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRA_FlujoxProceso> TRA_FlujoxProceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRA_Tramite> TRA_Tramite { get; set; }
    }
}
