//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Director
    {
        public int IdDirector { get; set; }
        public string Siglas { get; set; }
        public string NomDirector { get; set; }
        public string ApePDirector { get; set; }
        public string ApeMDirector { get; set; }
        public string Nombre { get; set; }
    }
}
