//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_permiso
    {
        public int id { get; set; }
        public int idPerfil { get; set; }
        public int idNombrePermiso { get; set; }
        public bool estatus { get; set; }
        public string idUsuarios { get; set; }
    
        public virtual CAT_nombrePermiso CAT_nombrePermiso { get; set; }
        public virtual CAT_perfil CAT_perfil { get; set; }
    }
}
