//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial2014
    {
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
        public Nullable<System.DateTime> FechaDePago { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> IdFolio { get; set; }
        public Nullable<int> FolioOperacion { get; set; }
        public Nullable<int> AñoPagado { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre { get; set; }
    }
}
