//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indices1
    {
        public int IdIndice { get; set; }
        public int Mes { get; set; }
        public int Anio { get; set; }
        public decimal Indice { get; set; }
        public Nullable<System.DateTime> Fecha_Publicacion { get; set; }
        public string Clave_Indices { get; set; }
        public Nullable<int> MesTranscurrido { get; set; }
        public Nullable<int> AnioMulta { get; set; }
    }
}
