//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operaciones
    {
        public int IdOperaciones { get; set; }
        public int Anio { get; set; }
        public int IdNomBim { get; set; }
        public decimal Factor { get; set; }
        public string ClaveOperaciones { get; set; }
    }
}
