//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_Nota
    {
        public long id { get; set; }
        public string tipoNota { get; set; }
        public string clave { get; set; }
        public string numeroDeCuenta { get; set; }
        public Nullable<int> idColonia { get; set; }
        public Nullable<int> manzana { get; set; }
        public string nota { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
