//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_HistorialBDViejo
    {
        public int Id { get; set; }
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
        public string ClaveCatastral { get; set; }
        public string TipoOperacion { get; set; }
        public string DescripcionOperacion { get; set; }
        public string Usuario { get; set; }
        public string Caja { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
    }
}
