//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_HistorialUsuario
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string aPaterno { get; set; }
        public string aMaterno { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<int> idPuesto { get; set; }
        public Nullable<int> idCoordinacion { get; set; }
        public Nullable<bool> idPerfilAccesoPredial { get; set; }
        public Nullable<bool> idPerfilAccesoGestion { get; set; }
        public Nullable<bool> idPerfilAccesoWeb { get; set; }
        public Nullable<bool> idPerfilAccesoCaja { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
        public Nullable<bool> permisoUsuarios { get; set; }
        public Nullable<bool> permisoPerfiles { get; set; }
        public Nullable<int> idPerfil { get; set; }
        public System.DateTime fechaDeBaja { get; set; }
        public int identificador { get; set; }
        public string UsuarioElimina { get; set; }
    }
}
