//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_HistorialPropietarios
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<int> Sexo { get; set; }
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<int> Manzana { get; set; }
        public Nullable<int> Predio { get; set; }
        public Nullable<int> Condominio { get; set; }
        public Nullable<int> TipoPropietario { get; set; }
        public string NombreComercial { get; set; }
        public string TelefonoFijo { get; set; }
        public string DireccionDeNotificacion { get; set; }
        public Nullable<int> IdColoniaDeNotificacion { get; set; }
        public string CURP { get; set; }
        public string RFC { get; set; }
        public string TelefonoMovil { get; set; }
        public Nullable<int> Municipio { get; set; }
        public Nullable<int> Edificio { get; set; }
        public Nullable<double> PorcentajePropiedad { get; set; }
        public Nullable<double> PorcentajeUsufructo { get; set; }
        public Nullable<double> PorcentajeNuda { get; set; }
        public Nullable<int> IdPersonaVulnerable { get; set; }
        public Nullable<bool> PersonaFisica { get; set; }
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
    }
}
