//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_RechazosTraslados
    {
        public int IdRechazo { get; set; }
        public string Clave { get; set; }
        public string ClaveCatastral { get; set; }
        public string NumeroDeCuenta { get; set; }
        public string ClaveOrigen { get; set; }
        public string NumeroDeCuentaOrigen { get; set; }
        public string ClaveCatastralOrigen { get; set; }
        public int Estatus { get; set; }
        public Nullable<int> Tarea { get; set; }
        public Nullable<int> NumeroTramite { get; set; }
    }
}
