//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_DetallesDeDescuentos
    {
        public int IdDetallesDescuentos { get; set; }
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
        public int IdTipoDescuento { get; set; }
        public int IdAñoDeDescuento { get; set; }
        public decimal Descuento { get; set; }
        public System.DateTime FechaDeAplicacion { get; set; }
        public Nullable<int> FolioOperacion { get; set; }
    }
}
