//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_HistorialMovimientosPredio
    {
        public int Id { get; set; }
        public string Clave { get; set; }
        public long NumeroDeCuenta { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaOperacion { get; set; }
        public int IdTipoOperacion { get; set; }
        public Nullable<int> IdTipoCampo { get; set; }
    
        public virtual CAT_TipoCambio CAT_TipoCambio { get; set; }
        public virtual CAT_TipoOperacion CAT_TipoOperacion { get; set; }
    }
}
