//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_HistorialPredios
    {
        public int Id { get; set; }
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<int> Manzana { get; set; }
        public Nullable<int> Predio { get; set; }
        public Nullable<int> Condominio { get; set; }
        public Nullable<int> IdColoniaDePredio { get; set; }
        public Nullable<int> IdTipoConstruccion { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public System.DateTime FechaBaja { get; set; }
        public string NombreCalle { get; set; }
        public string NumeroExterior { get; set; }
        public string NumeroInterior { get; set; }
        public Nullable<int> CodigoPostal { get; set; }
        public string UsuarioBaja { get; set; }
        public Nullable<decimal> SuperficieDeTerreno { get; set; }
        public Nullable<decimal> SuperficieDeConstruccion { get; set; }
        public Nullable<decimal> SuperficieUrbana { get; set; }
        public Nullable<decimal> SuperficiComercial { get; set; }
        public Nullable<decimal> SuperficieIndustrial { get; set; }
        public string ClaveCatastral { get; set; }
        public Nullable<int> Municipio { get; set; }
        public Nullable<int> Edificio { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> IdTipoDeVialidad { get; set; }
        public string ClaveOrigen { get; set; }
        public string NumeroDeCuentaOrigen { get; set; }
        public string ClaveCatastralOrigen { get; set; }
        public string Descripcion { get; set; }
        public bool esCambio { get; set; }
    }
}
