//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_DetallesDeTerreno_Temporal
    {
        public int Id { get; set; }
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<int> Manzana { get; set; }
        public Nullable<int> Predio { get; set; }
        public Nullable<int> Condominio { get; set; }
        public int Año { get; set; }
        public Nullable<decimal> AreaConstruccion { get; set; }
        public string UsoDeSuelo { get; set; }
        public int IdTipoDeConstruccion { get; set; }
        public Nullable<int> Municipio { get; set; }
        public Nullable<int> Edificio { get; set; }
    
        public virtual CAT_TipoConstruccion CAT_TipoConstruccion { get; set; }
    }
}
