//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_ParametrosRecargoBimestral
    {
        public int Id { get; set; }
        public int año { get; set; }
        public int idBimestre { get; set; }
        public Nullable<bool> aplicado { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
    }
}
