//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_HectareasCobradas
    {
        public int Id { get; set; }
        public decimal NumeroHectareas { get; set; }
        public string Clave { get; set; }
        public string Cuenta { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime AñoDePago { get; set; }
    }
}
