//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA_Rechazo
    {
        public int id { get; set; }
        public string MotivoRechazo { get; set; }
        public int idSolicitante { get; set; }
        public System.DateTime Fecharechazo { get; set; }
        public string NoTramite { get; set; }
        public int StatusAnterior { get; set; }
        public string CLaveCatastral { get; set; }
        public int IdProcesoAnterior { get; set; }
        public string nombreSolicitante { get; set; }
        public string AreaRechazo { get; set; }
        public bool EstadoActual { get; set; }
        public int idTareaAnterior { get; set; }
        public int IdUsuarioRechazo { get; set; }
    }
}
