//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA_ParametrosLeyDeIngresos
    {
        public int id { get; set; }
        public int año { get; set; }
        public decimal porceTraslado { get; set; }
        public decimal porceRecargo { get; set; }
        public decimal salariominimo { get; set; }
        public decimal RecargoExtra { get; set; }
    }
}
