//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA_Tramite
    {
        public int id { get; set; }
        public string clavecatastral { get; set; }
        public System.DateTime fechaInicial { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
        public int Estatus { get; set; }
        public string Observaciones { get; set; }
        public int IdTipoProceso { get; set; }
        public int IdUsuario { get; set; }
        public int Municipio { get; set; }
        public int region { get; set; }
        public int manzana { get; set; }
        public int predio { get; set; }
        public int edificio { get; set; }
        public int condominio { get; set; }
        public string numeroCuenta { get; set; }
        public string nroTramite { get; set; }
        public int Solicitante { get; set; }
        public string nombreSolicitante { get; set; }
        public string obsAclaracion { get; set; }
        public bool procede { get; set; }
        public string clave { get; set; }
        public string año { get; set; }
        public string consecutivo { get; set; }
        public string nombreApellidoPaterno { get; set; }
        public string nombreApellidoMaterno { get; set; }
        public string NumeroEscritura { get; set; }
    
        public virtual CAT_TRASLADOS_Solicitante CAT_TRASLADOS_Solicitante { get; set; }
        public virtual CAT_TRASLADOS_TipoProceso CAT_TRASLADOS_TipoProceso { get; set; }
    }
}
