//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA_Adeudo
    {
        public int id { get; set; }
        public string nroTramite { get; set; }
        public string clave { get; set; }
        public string cuenta { get; set; }
        public string clavecat { get; set; }
        public decimal baseACalcular { get; set; }
        public decimal baseGravable { get; set; }
        public decimal impuesto { get; set; }
        public decimal recargos { get; set; }
        public decimal CargoExtra { get; set; }
        public decimal condoImpuesto { get; set; }
        public decimal condoRecargo { get; set; }
        public decimal totalAdeudo { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public System.DateTime fechaGeneracionAdeudo { get; set; }
        public System.DateTime fechaInicioRecargos { get; set; }
        public int LeyIngresos { get; set; }
        public int DiasTranscurridos { get; set; }
        public decimal ValorFiscal { get; set; }
        public decimal ValorComercial { get; set; }
        public decimal ValorReferido { get; set; }
        public bool Pagado { get; set; }
        public int Descuento { get; set; }
        public string MotivoDescuento { get; set; }
        public int AñoLeyIngresos { get; set; }
        public string Porcentaje { get; set; }
    }
}
