//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioVisor
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string aPaterno { get; set; }
        public string aMaterno { get; set; }
        public string nombreUsuario { get; set; }
        public string contraseña { get; set; }
        public Nullable<bool> sesionIniciada { get; set; }
        public string idSesion { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string UsuarioQueDioAlta { get; set; }
        public string Notaria { get; set; }
    }
}
