//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLCNG.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISTA_ADEUDOS
    {
        public string Clave { get; set; }
        public string NumeroDeCuenta { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<decimal> BaseGravable { get; set; }
        public Nullable<decimal> AreaTerreno { get; set; }
        public string NombreCalle { get; set; }
        public string NombreDeVialidad { get; set; }
        public string Colonia { get; set; }
        public string NombreTipoColonia { get; set; }
        public string ClaveCatastral { get; set; }
        public string NumeroExterior { get; set; }
        public string NumeroInterior { get; set; }
        public string Lote { get; set; }
        public string Manzana { get; set; }
        public string Zona { get; set; }
        public string Parcela { get; set; }
        public int año { get; set; }
        public decimal Adeudo { get; set; }
        public Nullable<decimal> Recargo { get; set; }
        public Nullable<decimal> CondonacionGeneral { get; set; }
        public Nullable<decimal> Multa { get; set; }
        public Nullable<int> IdColoniaDePredio { get; set; }
        public Nullable<int> IdManzana { get; set; }
    }
}
